[package]
name = "proxybench"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
reqwest = "0.12.8"
tokio = { version = "1.41.0", features = ["full"] }
